name: validate XSD
on:
 workflow_dispatch:
 pull_request:
  paths:
   - "./github/scripts/validate_xsd.py"
env:
 FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
 FILE_PY: ./github/scripts/validate_xsd.py
jobs:
 validate:
  runs-on: ubuntu-latest
  steps:
   - name: checkout repo
     uses: actions/checkout@v5
   - name: setup Python
     uses: actions/setup-python@v6
     with:
      python-version: '3.14'
   - name: install XML library
     run: pip install lxml
   - name: validate
     run: |
      find -type f -name "*.xsd" -exec python $FILE_PY {} \;